### ISSUE TITLE
Improve `onSelect`

### ISSUE THREAD

**Issue by sibelius** [vincentsylo/react-native-checkbox-field#8]
I think it makes sense to `onSelect` receive if the checkbox should go to a checked state or to an unchecked state

something like this:

```js
onSelect(checked) => {
    if (checked) console.log('checkbox was selected')
    else console.log('checkbox was unselected')
 }
```

**Comment by vincentsylo** [comment]
Sorry for getting back to this issue 10 months later, I haven't had much of a chance to revisit this package however have cleaned it up a fair bit (v2.0.2 now)

My preference is for this component to not maintain state within the CheckboxField, but having the higher order component pass it down via props. 

This would mean that you can get your checked value via:

```
state = {
  selected: false,
};

onSelect = () => {
  const { selected } = this.state;
  const checked = !selected;

  console.log(`checkbox was ${checked ? 'selected' : 'unselected'}`);
  this.setState({
    selected: checked,
  });
};

render() {
  return (
    <CheckboxField
      label="Field"
      onSelect={this.onSelect}
      selected={this.state.selected}
    >
      <Text>Y</Text>
    </CheckboxField>
  )
}
```
